#!/usr/bin/env node
// Renders catalog/README.md and one page per category from data/mods.json
// and data/stats.json. Deterministic: the same data gives the same bytes.
//
//   node scripts/build-catalog.mjs          write catalog/
//   node scripts/build-catalog.mjs --check  exit 1 if catalog/ is stale (CI)

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  CATEGORIES,
  UI_LEGEND,
  escapeCell,
  escapeLabel,
  escapeUrl,
  formatStars,
  isNew,
  uiIcons,
} from './lib/mods-index.mjs'

const root = join(fileURLToPath(import.meta.url), '..', '..')
const CATALOG = join(root, 'catalog')
const isCheck = process.argv.includes('--check')

const mods = JSON.parse(readFileSync(join(root, 'data', 'mods.json'), 'utf8'))
const stats = JSON.parse(readFileSync(join(root, 'data', 'stats.json'), 'utf8'))

const ROWS_PER_PAGE = 500
const MAX_PAGE_BYTES = 400_000
const fmt = n => n.toLocaleString('en-US')

const modLink = m => `[${escapeLabel(m.name)}](${escapeUrl(m.url)})`
const repoLink = m => `[${escapeLabel(m.repo)}](https://github.com/${escapeUrl(m.repo)})`
const license = m => (m.license === null || m.license === 'NOASSERTION' ? '—' : escapeCell(m.license))

function row(m, n) {
  return `| ${n} | ${modLink(m)} | ${repoLink(m)} | ${formatStars(m.stars)} | ${escapeCell(m.description) || '—'} | ${uiIcons(m)} | ${license(m)} | ${m.pushedAt ?? '—'} |`
}

const TABLE_HEAD = '| # | Mod | Repo | ★ | What it does | UI | License | Updated |\n| ---: | --- | --- | ---: | --- | :-: | --- | --- |'

const pageName = (id, page) => (page === 1 ? `${id}.md` : `${id}-${page}.md`)

function paginate(list) {
  const pages = []
  let current = []
  let bytes = 0
  list.forEach((m, i) => {
    const line = row(m, i + 1)
    if (current.length > 0 && (current.length >= ROWS_PER_PAGE || bytes + line.length > MAX_PAGE_BYTES)) {
      pages.push(current)
      current = []
      bytes = 0
    }
    current.push(line)
    bytes += line.length + 1
  })
  if (current.length > 0) pages.push(current)
  return pages
}

const files = new Map()
const pageCounts = new Map()
const HEADER = '<!-- Generated by scripts/build-catalog.mjs from data/mods.json. Do not edit by hand. -->'

for (const category of CATEGORIES) {
  const list = mods.filter(m => m.category === category.id)
  const pages = paginate(list)
  pageCounts.set(category.id, pages.length)
  pages.forEach((lines, i) => {
    const page = i + 1
    const nav = pages.length > 1
      ? `\nPage ${page} of ${pages.length}: ${pages.map((_, j) => (j === i ? `**${j + 1}**` : `[${j + 1}](${pageName(category.id, j + 1)})`)).join(' · ')}\n`
      : ''
    const text = [
      HEADER,
      `# ${category.emoji} ${category.title}`,
      '',
      `*${category.blurb}* ${fmt(list.length)} mods, most starred first. Updated ${stats.updated}.`,
      '',
      `[← The full index](README.md) · [Curated list](../README.md) · ${UI_LEGEND}`,
      nav,
      TABLE_HEAD,
      ...lines,
      '',
      'Categories are picked automatically from each mod\'s name, description and code. [Open an issue](https://github.com/Singh-AP/awesome-claude-mods/issues/new?template=bug.yml) if one is wrong.',
      '',
    ].join('\n')
    files.set(pageName(category.id, page), text)
  })
}

function shortList(list) {
  return [
    '| Mod | Repo | ★ | What it does | UI |',
    '| --- | --- | ---: | --- | :-: |',
    ...list.map(m => `| ${modLink(m)} | ${repoLink(m)} | ${formatStars(m.stars)} | ${escapeCell(m.description) || '—'} | ${uiIcons(m)} |`),
  ].join('\n')
}

const fresh = mods.filter(m => isNew(m, stats.updated)).slice(0, 25)
const top = mods.slice(0, 50)

const index = [
  HEADER,
  '# The full index: every public Claude Code mod',
  '',
  `**${fmt(stats.mods)} mods** in **${fmt(stats.repos)} repos** · ${fmt(stats.withUi)} draw something · ${fmt(stats.licensed)} carry an open-source license · ${fmt(stats.newThisWeek)} new this week · updated **${stats.updated}**`,
  '',
  'A scanner runs every day, and the [curated list](../README.md) has the hand-picked best. It searches GitHub for plugins whose `hooks/hooks.json` lists `modules`, reads each module, and keeps the real mods: copies of other mods, forks, test fixtures and templates are left out. Nothing here has been reviewed by a person. Read a mod before you install it.',
  '',
  '## Browse by category',
  '',
  '| Category | Mods | |',
  '| --- | ---: | --- |',
  ...CATEGORIES.map(c => `| ${c.emoji} [${c.title}](${pageName(c.id, 1)}) | ${fmt(stats.byCategory[c.id] ?? 0)} | ${c.blurb} |`),
  '',
  `UI: ${UI_LEGEND}`,
  '',
  '## 🆕 New this week',
  '',
  fresh.length > 0 ? shortList(fresh) : '*Nothing new in the last seven days.*',
  '',
  '## 🔥 Most starred',
  '',
  'Stars are the whole repository\'s, not the mod\'s.',
  '',
  shortList(top),
  '',
  '## Get listed, or unlisted',
  '',
  'There\'s nothing to do: a public repo with a mod is found within a day. To be left out, or to report a wrong category or description, [open an issue](https://github.com/Singh-AP/awesome-claude-mods/issues/new/choose). The raw data is in [`data/mods.json`](../data/mods.json), one mod per line.',
  '',
].join('\n')
files.set('README.md', index)

let stale = []
const existing = existsSync(CATALOG) ? readdirSync(CATALOG).filter(f => f.endsWith('.md')) : []
for (const [name, text] of files) {
  const path = join(CATALOG, name)
  if (existsSync(path) && readFileSync(path, 'utf8') === text) continue
  stale.push(name)
  if (!isCheck) {
    mkdirSync(CATALOG, { recursive: true })
    writeFileSync(path, text)
  }
}
for (const name of existing) {
  if (files.has(name)) continue
  stale.push(name)
  if (!isCheck) rmSync(join(CATALOG, name))
}

if (isCheck) {
  if (stale.length > 0) {
    console.error(`✘ catalog/ is out of date (${stale.join(', ')}): run node scripts/build-catalog.mjs`)
    process.exit(1)
  }
  console.log('✔ catalog/ is up to date')
} else {
  const biggest = Math.max(...[...files.values()].map(t => Buffer.byteLength(t)))
  console.log(`catalog: ${files.size} pages, ${stale.length} written or removed, largest ${Math.round(biggest / 1024)} KB`)
}
