#!/usr/bin/env node
// Runs `claude plugin validate --strict` or `claude plugin test` on every mod
// in the repo (or the ones named on the command line) and summarises.
//
//   node scripts/each-mod.mjs validate [mod-name...]
//   node scripts/each-mod.mjs test [mod-name...]
//
// CLAUDE_BIN picks the Claude Code binary (default: `claude` on PATH).

import { spawnSync } from 'node:child_process'
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(fileURLToPath(import.meta.url), '..', '..')
const bin = process.env.CLAUDE_BIN || 'claude'
const args = process.argv.slice(2)
const shouldUpdateCount = args.includes('--update-count')
const shouldWriteCapabilities = args.includes('--write-capabilities')
const capabilities = []
const [action, ...only] = args.filter(a => !a.startsWith('--'))

if (action !== 'validate' && action !== 'test') {
  console.error('usage: each-mod.mjs validate|test [mod-name...]')
  process.exit(2)
}

export function findMods(base = join(root, 'mods')) {
  const mods = []
  for (const category of readdirSync(base, { withFileTypes: true })) {
    if (!category.isDirectory()) continue
    for (const mod of readdirSync(join(base, category.name), { withFileTypes: true })) {
      const dir = join(base, category.name, mod.name)
      if (mod.isDirectory() && existsSync(join(dir, '.claude-plugin', 'plugin.json'))) mods.push(dir)
    }
  }
  return mods.sort()
}

const mods = findMods().filter(dir => only.length === 0 || only.some(name => dir.endsWith(`/${name}`)))
const failed = []
let testTotal = 0

if (action === 'validate') {
  const marketplace = spawnSync(bin, ['plugin', 'validate', '--strict', root], { encoding: 'utf8' })
  if (marketplace.status !== 0) failed.push(['marketplace', marketplace.stdout + marketplace.stderr])
  else console.log('✔ marketplace')
}

for (const dir of mods) {
  const args = action === 'validate' ? ['plugin', 'validate', '--strict', '--json', dir] : ['plugin', 'test', dir]
  const run = spawnSync(bin, args, { encoding: 'utf8', cwd: dir })
  if (action === 'validate') {
    try {
      const report = JSON.parse(run.stdout)
      const notes = report.contents.flatMap(c => c.notes ?? [])
      const pick = word => (notes.find(n => n.includes(` ${word}: `)) ?? '').split(`${word}: `)[1] ?? ''
      capabilities.push({ name: relative(root, dir), hooks: pick('hooks'), calls: pick('calls') })
    } catch {
      // A report that isn't JSON is a failure the exit status already shows.
    }
  }
  const name = relative(root, dir)
  if (run.status === 0) {
    const passed = Number(run.stdout.match(/(\d+) pass/)?.[1] ?? 0)
    testTotal += passed
    const tally = action === 'test' ? `${passed} tests` : 'valid'
    console.log(`✔ ${name} (${tally})`)
  } else {
    console.log(`✘ ${name}`)
    failed.push([name, run.stdout + run.stderr])
  }
}

if (action === 'validate' && shouldWriteCapabilities && failed.length === 0 && only.length === 0) {
  writeFileSync(join(root, 'docs', 'capabilities.md'), capabilitiesPage(capabilities))
  console.log('wrote docs/capabilities.md')
}

for (const [name, output] of failed) console.error(`\n── ${name} ──\n${output.trim()}`)

// `--update-count` records the total in registry.json, which feeds the README badge.
if (action === 'test' && shouldUpdateCount && failed.length === 0 && only.length === 0) {
  const path = join(root, 'registry.json')
  const registry = JSON.parse(readFileSync(path, 'utf8'))
  registry.testCount = testTotal
  writeFileSync(path, JSON.stringify(registry, null, 2) + '\n')
  console.log(`registry.json testCount = ${testTotal}`)
}
console.log(`\n${mods.length - failed.filter(([n]) => n !== 'marketplace').length}/${mods.length} mods passed ${action}`)
process.exit(failed.length === 0 ? 0 : 1)

function capabilitiesPage(rows) {
  const flags = [
    ['🌐', 'network', /\$\.http\./],
    ['⚙️', 'runs commands', /\$\.process\./],
    ['🧠', 'calls a model', /\$\.model\./],
    ['📝', 'writes files', /\$\.fs\.write/],
    ['🔧', 'sees or changes tool calls', /tool\.call/],
    ['✂️', 'rewrites transcript rows', /session\.append/],
    ['🧾', 'edits the system prompt', /prompt\.compose|prompt\.section/],
  ]
  const lines = [
    '<!-- Generated by `node scripts/each-mod.mjs validate --write-capabilities` from `claude plugin validate --json`. Do not edit. -->',
    '# What each mod can touch',
    '',
    "Claude Code's own static analyzer (`claude plugin validate`) reads each mod's source and lists every event it hooks and every API it calls. This page is that output, regenerated in CI, so a mod can't quietly gain a capability.",
    '',
    'Legend: ' + flags.map(([icon, label]) => `${icon} ${label}`).join(' · '),
    '',
    '| Mod | Can | Hooks | Calls |',
    '| --- | --- | --- | --- |',
  ]
  for (const row of rows) {
    const text = `${row.hooks} ${row.calls}`
    const can = flags.filter(([, , pattern]) => pattern.test(text)).map(([icon]) => icon).join(' ')
    const name = row.name.split('/').pop()
    const clean = value => value.replace(/\|/g, '\\|').replace(/ \(via [^)]*\)/g, '') || '—'
    lines.push(`| [${name}](../${row.name}/) | ${can || '—'} | ${clean(row.hooks)} | ${clean(row.calls)} |`)
  }
  return lines.join('\n') + '\n'
}
